# Introduction to the GTAA  {-} 

<span style="color:red;font-weight:700;font-size:32px">THIS IS A DEMO!</span>  

The **Global Tactical Asset Allocation Strategy(GTAA)** is a top-down global macro strategy that seeks to identify and exploit inefficiencies between markets, regions, countries, and sectors. The research and decision-making process is fundamentally-driven and discretionary, but supported by an extensive quantitative research platform. The Strategy invests across global asset classes, including stocks, bonds, currencies and commodities. (https://www.morganstanley.com/im/en-us/individual-investor/strategies/solutions-and-multi-asset/global-tactical-asset-allocation.html)

The GTAA Investment Strategy  

* GTAA (Global Tactical Asset Allocation) is a top-down investment strategy.  

* Our GTAA strategies adapts heavily from the All-weather Strategy by Bridgewater Associates.  

* Strategy attempts to utilize various types of asset classes globally (Equities, ETFs, Bonds, FXs, and Cash) to capture maximum risk-adjusted returns for the entire duration of our investment.  

*	The advantage in adapting the strategy is the fixability in adjusting allocation among assets (asset class, regions, sectors)  

* The basis of the strategy is the Marking Timing Hypothesis, a widely applied multi-asset portfolio management methodology in mimicking risks. Investors are able to rely on the strategy in determining when to enter or exit risky/high yield assets classes into the less-risky ones.   

* Strategy characteristics: 
o	Highly diversified 
o	Invest across a wide selection of global assets
o	Taking positions across multiple asset classes 
o	Increased hedge tools   
o	Highly flexible & reliable (All-weather)  

策略构建
• 投资范围（资产类别）
  - 全球股票（基准：纳斯达克100指数、MSCI全球指数、MSCI新兴市场指数等）
  - 全球政府债券
  - 全球高收益公司债券*
  - 外汇
  - ETF（交易所交易基金）
  - 商品期货合约（黄金、白银、原油等）
• 研究基础
  - 自上而下的全球宏观策略：利用市场、地区、国家和行业之间的投资时效性差异。
  - 决策制定：基于基本面和自主判断，来源于深入的量化研究。
• 全球宏观 + 基本面 + 量化 + 多资产类别头寸。
• 探索结构性不足（misprice）、相关性较弱的投资机会以及宏观经济转折点带来的超额收益。


`In Progress`


## GTAA Philosphy {-} 


Asset class selection. An output of this model would be long or short positions in global stocks, global bonds and cash . One can think of global stocks or global bonds as of respective world indices, not necessarily weighted according to market capitalisation. They may also be weighted by GDP or just equally;
Stock country selection. This model compares country stock markets to each other and results in a dollar-neutral long-short portfolio of equity markets;
Bond country selection. Ditto for bond markets;
Tactical currency allocation. This model's recommendations are long and short positions in currencies. These positions add up to zero.(https://thehedgefundjournal.com/global-tactical-asset-allocation/)

`In Progress`

## Investment Scope {-} 

Portfolio Construction:  

*	Example: Use EM and Tech stocks as the major risky assets, hedge by 10Y US-Govt Bonds, Gold futures and Cash/CDs  

* Asset allocation and timing (TAA): the allocation percentages are heavily dependent on global macros, fundamentals, and quantitative asset allocation and portfolio optimization models. 
* Investment timing: when to enter or exit positions.  

* Investment class choices: Equities vs. FI products, small cap vs. large cap, value vs growth
* Global scope and timing (G): region, country and sector selections within asset classes: DM vs EM (FI products, Equities, ETFs, FX deviations) and which specific country/region

The Global Multi-Asset team believes that global multi-asset class investing presents opportunities to generate excess return due to structural inefficiencies such as home-country bias and the tendency for a majority of investors to focus on security selection. In addition, regions and countries have independent economic drivers, which often give rise to uncorrelated investment opportunities.  We also believe that investors have a tendency to extrapolate current trends into the future, mistaking cyclical dynamics for structural changes, and vice versa.  We therefore invest around major macro-economic turning points, where we think investors are most likely to mis-price assets amid changing dynamics. 

投资组合构建：

• 示例：以新兴市场和科技股作为主要的风险资产，通过美国10年期政府债券、黄金期货和现金/定期存款进行对冲。
• 资产配置和择时（TAA）：配置比例依赖于全球宏观经济、基本面的深度研究和资产配置及投资组合优化的多策略量化模型。
  - 投资时机：何时进入或退出头寸。
  - 投资类别选择：股票与固定收益产品、小盘股与大盘股、价值股与成长股。
• 全球范围和时机（G）：在资产类别内选择地区、国家和行业：
  - 发达市场与新兴市场（固定收益产品、股票、ETF、外汇波动）及具体的国家/地区。


`In Progress` 



## Investment & Research Process {-} 

Investment Research Process-GTAA-based Portfolio  

* Our team maintains an active management approach in constructing portfolios with maximized upside risk-adjusted returns in the long-run that’s appropriate to the investors’ investment needs and risk tolerance.  

* Selecting across various asset classes and securities around the global that are the most appropriate given current market dynamics aiming for maximum long-term risk-adjusted returns while controlling the max drawdown proactively.  

*Risk Management: moderate risk preference in asset allocations and active risk management for security-specific risks and sudden market shifts. Tools include stop-loss levels, stress tests and internal risk management team.  

Investment research is based on asset classes:  

o	Equities: Fundamentals, Global Macro, Sector analysis, Quantitative Stock-selection Model with Backtest.  

o	Fixed Income: Fundamentals, Credit (sector & company-specific), macros, gov bond quant model? 
o	FXs: Fundamentals, Global Macro.  

o	ETFs: Fundamentals, Global Macro.  

o	 Commodities: Fundamentals, Global Macro, Quantitative pricing model?  

•	Asset Allocation:  

o	One of the advantages in adapting a GTAA portfolio is the Asset allocation and timing (TAA).   

o	Asset allocation is dependent on global macros, and PM experiences.  

o	Tools developed in validating asset allocation: Quantitative Portfolio Asset Allocation Model (Tactical Asset Allocation).   

	Purpose: Validate allocation/investment portfolio rebalancing ideas are in alignment with the current global macros and market landscape statistics (benchmarks).  




投资研究流程 - 基于GTAA的投资组合

• 我们的团队采取主动管理的模式，以构建可长期持有的投资组合为目的，最大化风险调整回报，同时符合投资者的投资需求和风险承受能力。
• 在全球范围内选择各种资产类别和证券，在考虑当前市场动态下，旨在实现最大的长期风险调整回报，同时积极控制最大回撤。
• 风险管理：在资产配置上偏好中度风险，并针对特定证券风险和突发市场变动进行积极的风险管理。工具包括：止损水平线、组合回测、压力测试和内部风险管理团队。
• 投资研究基于资产类别：
  - 股票：基本面、全球宏观、行业分析、具有回测功能的量化选股模型
  - 固定收益：基本面、信用（行业和公司特定）、宏观经济、政府债券量化模型？
  - 外汇：基本面、全球宏观
  - ETF：基本面、全球宏观
  - 大宗商品：基本面、全球宏观、定量定价模型？
• 资产配置：
  - 在采用GTAA投资组合的优势之一是资产配置和择时（TAA）。
  - 资产配置取决于全球宏观经济和投资经理的投资经验。
  - 工具开发用于验证组合资产配置比例：量化投资组合资产配置模型（TAA）。
- 目的：验证资产配置/投资组合再平衡想法与当前全球宏观经济和市场格局统计数据（基准）的一致性。
• 风险管理：

The Global Multi-Asset team offers investors access to an investment approach focusing on opportunities arising from macroeconomic changes and structural transformations that have not yet been discounted in valuations. The team’s investment process seeks to identify attractive risk/reward opportunities based on three primary criteria: valuation, fundamental dynamics, and sentiment. The team believes that these three tools are most powerful when used in combination. The team invests in opportunities at the asset class, country, sector and thematic levels, rather than concentrating on individual security selection.  


`In Progress`



## Risk Management {-} 

`In Progress`
