# Quick Table of Contents 快速索引{-}  

#### <span style="font-weight:700;font-size:17px">Into on Global Multi-asset Strategy 全球多资产策略</span> {-} 

* [Introduction to the GTAA] for the overview on the Global Tactical Asset Allocation Strategy   [`Multi-asset Strategy Overview`]   

#### <span style="font-weight:700;font-size:17px">The Base Model: a Technical Signaling Tool for Stock Selection 基础模型：技术指标选股工具</span> {-} 

* [Investment Strategy Outlook 投资策略及模型规划] for **Investment Thesis** and **Model Planning & Considerations** [`Stock Selection Model (Base)`]   

* [(Base) Model Construction 基础模型搭建] for **Model Construction** steps and the **Subjective Filters** [`Stock Selection Model (Base)`]  

* [Technical Indicators Construction 技术指标搭建] for the construction of all **Technical Indicators** used [`Stock Selection Model (Base)`]  

* [Selecting Effective Technical Indicators 选取有效的技术指标] for the **dynamically** selection process of the **significant** **technical indicators** [`Stock Selection Model (Base)`]  

* [(Base) Model Performance 模型选股表现] for the `base` **model performance** and backtest results [`Stock Selection Model (Base)`]  


#### <span style="font-weight:700;font-size:17px">The Complete Model: a Comprehensive Stock Selection Model: Using Quantitative Indicators 完整模型：基于量化指标的全面选股工具</span> {-} 

`TBD`


* [Risk Disclosure 风险披露] for the model and portfolio **risks** [`Multi-asset Strategy Quant Approach`]  

* [Appendix 附录] for the codes and our resources [`Multi-asset Strategy Quant Approach`]   



